services:
  backend:
    build: 
      context: ./user_preference/backend-app
    container_name: backend
    ports:
      - 3000:3000
    depends_on:
      - mongo
    networks:
      - app-networks
  
  frontend:
    build: 
      context: ./user_preference/frontend-app
    container_name: frontend
    ports:
      - 8080:8080
    networks:
      - app-networks
    
  mongo:
    image: mongo:4.4.6
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    networks:
      - app-networks
  
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
    networks:
      - app-networks

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTNER: PLAINTEXT://kafka:9092
    depends_on:
      - zookeeper
    networks:
      - app-networks
  
  python-app:
    build: 
      context: ./src
    container_name: python_app
    depends_on:
      - kafka
      - backend
    networks:
      - app-networks
    
volumes:
  mongo-data:

networks:
  app-networks: